.\"	$OpenBSD$
.\"
.\" Copyright (c) 2025 Tobias Heider <tobhe@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: November 21 2025 $
.Dt DISKINFO 1
.Os
.Sh NAME
.Nm diskinfo
.Nd display disk information
.Sh SYNOPSIS
.Nm diskinfo
.Op Fl h
.Nm diskinfo
.Op Fl h
.Ar disk
.Sh DESCRIPTION
The
.Nm
utility displays information about the specified
.Ar disk .
If no operands are specified,
information for all available disks is displayed.
By default, size values are displayed as 512-byte block counts.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
"Human-readable" output.
Use unit suffixes: Byte, Kilobyte, Megabyte,
Gigabyte, Terabyte, Petabyte, Exabyte in order to reduce the number of
digits to four or less.
.Sh EXAMPLES
Output information for all available disks:
.Pp
.Bd -literal
# diskinfo
DISK                        TOTAL         FSTYPE        MOUNT
sd0:e0da951523552d12 [QEMU QEMU HARDDISK]
|-- sd0a	      976240591	   RAID
|-- sd0c	      976773168	 unused
`-- sd0i	         532480	  MSDOS

sd1:61992282be82044b [QEMU QEMU CRYPTO]
|-- sd1a	        2097152	 4.2BSD	/
|-- sd1b	       67461472	   swap
|-- sd1c	      976240063	 unused
`-- sd1i	         532480	  MSDOS
.ed
.Sh SEE ALSO
.Xr disklabel 5 ,
.Xr mount 8 ,
.Xr getmntinfo 3 ,
.Xr sd 4 ,
.Xr fstab 5 ,
